### PR TITLE
[nextjs] Move the import startsWith next check at end

### LINKED ISSUE #204: Importing next/link in `async` component produces error
### Steps to reproduce

Link to live example: (required)

Steps:
1. Do PigmentCSS migration on new nextjs project with MUI V6
2. Use `next/link` in async component

   ```js
    import { List, ListItemButton, ListItemText } from "@mui/material";
    import NextLink from "next/link";
    
    export default async function Home() {
      return (
        <List sx={{ width: "100%", height: "100%", overflowY: "scroll" }}>
          <ListItemButton href={{ pathname: `/documents` }} component={NextLink}>
            <ListItemText primary={"gg"} />
          </ListItemButton>
        </List>
      );
    }

   ```

### Current behavior

```
EvalError: Cannot assign to read only property '__esModule' of object '[object Object]' in/app/node_modules/next/dist/client/link.js
| /app/node_modules/next/link.js
| /app/app/page.tsx

    at Module.evaluate (/app/node_modules/@wyw-in-js/transform/lib/module.js:224:13)
    at require.Object.assign.ensure (/app/node_modules/@wyw-in-js/transform/lib/module.js:118:7)
    at newRequire (/app/node_modules/@pigment-css/unplugin/build/index.js:110:12)
    at /app/node_modules/next/link.js:1:40
    at /app/node_modules/next/link.js:3:3
    at Script.runInContext (node:vm:148:12)
    at Module.evaluate (/app/node_modules/@wyw-in-js/transform/lib/module.js:209:14)
    at require.Object.assign.ensure (/app/node_modules/@wyw-in-js/transform/lib/module.js:118:7)
    at newRequire (/app/node_modules/@pigment-css/unplugin/build/index.js:110:12)
    at /app/app/page.tsx:14:36
    at /app/app/page.tsx:166:3
    at Script.runInContext (node:vm:148:12)
    at Module.evaluate (/app/node_modules/@wyw-in-js/transform/lib/module.js:209:14)
    at evaluate (/app/node_modules/@wyw-in-js/transform/lib/evaluators/index.js:14:5)
    at BaseAction.evalFile (/app/node_modules/@wyw-in-js/transform/lib/transform/generators/evalFile.js:35:43)
    at evalFile.next (<anonymous>)
    at /app/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:66:78
    at EventEmitter.action (/app/node_modules/@wyw-in-js/transform/lib/utils/EventEmitter.js:25:22)
    at BaseAction.emitAction (/app/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:131:39)
    at nextFn (/app/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:66:32)
    at processNext (/app/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:111:28)
    at Object.next (/app/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:120:9)
    at asyncActionRunner (/app/node_modules/@wyw-in-js/transform/lib/transform/actions/actionRunner.js:39:102)
    at async asyncActionRunner (/app/node_modules/@wyw-in-js/transform/lib/transform/actions/actionRunner.js:46:22)
    at async Object.transform (/app/node_modules/@wyw-in-js/transform/lib/transform.js:107:20)
    at async Object.transform (/app/node_modules/@pigment-css/unplugin/build/index.js:273:24)
    at async Object.transform (/app/node_modules/unplugin/dist/webpack/loaders/transform.js:108:15)
 ⨯ unhandledRejection: /app/node_modules/@wyw-in-js/transform/lib/module.js:224
      throw new EvalError(`${e.message} in${this.callstack.join('\n| ')}\n`);
```

### Expected behavior

No error

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 
  System:
    OS: macOS 14.3.1
  Binaries:
    Node: 22.5.1 - /opt/homebrew/bin/node
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 9.6.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.100
    Edge: Not Found
    Safari: 17.3.1
  npmPackages:
    @emotion/react:  11.13.0 
    @emotion/styled:  11.13.0 
    @mui/core-downloads-tracker:  6.0.0-dev.240424162023-9968b4889d 
    @mui/icons-material: next => 6.0.0-beta.5 
    @mui/material: next => 6.0.0-beta.5 
    @mui/material-pigment-css: next => 6.0.0-beta.5-dev.20240809-114550-93cb3d65e7 
    @mui/private-theming:  6.0.0-beta.5-dev.20240809-114550-93cb3d65e7 
    @mui/styled-engine:  6.0.0-beta.5 
    @mui/system:  6.0.0-beta.5-dev.20240809-114550-93cb3d65e7 
    @mui/types:  7.2.15 
    @mui/utils:  6.0.0-beta.5-dev.20240809-114550-93cb3d65e7 
    @types/react: ^18 => 18.3.3 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1 
    typescript: ^5 => 5.5.4 

```
</details>

**Search keywords**: next/link pigmentcss

**Search keywords**:

### PR DESCRIPTION
**Pull request by brijeshb42**
* This fixes the resolve error happening in nextjs for it's path based module imports.
* Also adds check for `next/link`
* Ignore null value during css object processing

Fixes #204 

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/pigment-css/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/pigment-css-nextjs-plugin/src/index.ts [hunk 1]
```diff
@@ -76,6 +70,12 @@ export function withPigment(nextConfig: NextConfig, pigmentConfig?: PigmentOptio
           if (what.startsWith('@emotion/styled') || what.startsWith('styled-components')) {
             return require.resolve('../third-party-styled');
           }
+          // Need to point to the react from node_modules during eval time.
+          // Otherwise, next makes it point to its own version of react that
+          // has a lot of RSC specific logic which is not actually needed.
+          if (what.startsWith('@babel') || what.startsWith('react') || what.startsWith('next')) {
```
Comment (Janpot) [inline packages/pigment-css-nextjs-plugin/src/index.ts:76]: Is this strict enough? Would there be a risk matching on e.g. `react-hook-form`, `next-auth`,...

```suggestion
          if (what.startsWith('@babel/') || what.startsWith('react/') || what.startsWith('react-dom/') || what.startsWith('next/')) {
```

File: packages/pigment-css-react/src/utils/cssFnValueToVariable.ts [hunk 2]
```diff
@@ -155,6 +155,10 @@ function iterateAndReplaceFunctions(
   const css = styleObj as StyleObj;
   Object.keys(css).forEach((key) => {
     const value = css[key];
+    if (!value) {
+      // ignore null value
+      return;
+    }
```
Comment (siriwatknp) [inline packages/pigment-css-react/src/utils/cssFnValueToVariable.ts:161]: Can you review this instead https://github.com/mui/pigment-css/pull/229

**Review by Janpot — APPROVED** [review]

File: packages/pigment-css-nextjs-plugin/src/index.ts [hunk 3]
```diff
@@ -61,13 +61,7 @@ export function withPigment(nextConfig: NextConfig, pigmentConfig?: PigmentOptio
...
             return require.resolve('../next-font');
           }
-          // Need to point to the react from node_modules during eval time.
-          // Otherwise, next makes it point to its own version of react that
-          // has a lot of RSC specific logic which is not actually needed.
-          if (what.startsWith('@babel') || what.startsWith('react') || what.startsWith('next')) {
-            return require.resolve(what);
-          }
-          if (what === 'next/image') {
+          if (what === 'next/image' || what === 'next/link') {
```
Comment (flaviendelangle) [inline packages/pigment-css-nextjs-plugin/src/index.ts:64]: If `what==='next/link'` we still import `next-image`? @brijeshb42

Comment (brijeshb42) [reply packages/pigment-css-nextjs-plugin/src/index.ts:64]: Both just point to a dummy module for wyw evaluation to work.

Comment (brijeshb42) [reply packages/pigment-css-nextjs-plugin/src/index.ts:64]: next/link just provides a default export which is already there in the next-image file.

Comment (flaviendelangle) [reply packages/pigment-css-nextjs-plugin/src/index.ts:64]: OK :ok_hand:

Comment (Janpot) [reply packages/pigment-css-nextjs-plugin/src/index.ts:64]: That's a bit confusing 🙂

Comment (brijeshb42) [reply packages/pigment-css-nextjs-plugin/src/index.ts:64]: We could just rename the next-image file to `next-module-stub` or similar to remove the confusion.
It's on our side and not user facing.
